name: Scraping & Update CSV

on:
  schedule:
    - cron: "0 1 * * *" # Tous les jours à 01h00
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scraping/requirements.txt

      - name: Run scraping
        run: python scraping/scrape.py

      - name: Commit & Push CSV
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/ingredient_scrapees.csv
          git add data/recettes_scrapees.csv
          git commit -m "Update CSV automatically" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
